### PR TITLE
Enhance: show warning when spec-version not found

### PR DESCRIPTION
**Pull request by wkentaro**
to fix: https://github.com/vcstools/wstool/issues/41

### CODE REVIEW

**Comment by wjwwood** [comment]
lgtm

Can you post an example of what the output looks like after this change? I guess it just adds one more line of output with more information as to why it failed?

**Comment by wkentaro** [comment]
The output will be like:
```
% wstool info
tips: not found spec version master
workspace: /Users/ken/ws/ws_vcstools

 Localname         S SCM  Version-Spec UID  (Spec)                 URI  (Spec) [http(s)://...]
 ---------         - ---- ------------ -----------                 ---------------------------
 tips              V git  master       1492c2b33489 ("master")     github.com/wkentaro/tips.git
 vcstools/vcstools   git  master       9ae730caf74e                github.com/vcstools/vcstools.git
 vcstools/wstool   V git  master       3184cda3631e (11a87f40bdce) github.com/vcstools/wstool.git
 tkruse/wstool       git  divergence   9a4fbedab28d                github.com/tkruse/wstool.git
 tkruse/vcstools     git  divergence   f16548f5198d                github.com/tkruse/vcstools.git
```
the repo `tips`'s specified version is master, but I deleted it.

**Comment by tkruse** [comment]
At least we should change the error message, something like:
```warning: version 'xyz' not found for 'tips'```

However there are more problems here. The other VCSes still produce utput clutter (not using no_warn), and the message is also printed when using --yaml, which would break scripts using --yaml.

I think both things ought to be fixed.
Here is the .rosinstall I use for testig, with a repo in each VCS:

```
- bzr: {local-name: tomdroid, uri: 'lp:tomdroid', version: 'notexist'}
- hg: {local-name: javahg, uri: 'https://bitbucket.org/aragost/javahg', version: 'notexist'}
- svn: {local-name: ccv-code, uri: 'svn://svn.code.sf.net/p/ccv/code/trunk', version: 'notexist'}
- git: {local-name: vcstools, uri: 'git@github.com:vcstools/vcstools.git', version: 'notexist'}
```

To reproduce, I guess you shold remove the invalid version, do wstool update, then re-add, then run wstool info.

So I see these tasks:
- [ ] better wording and use of hyphens in warning message
- [ ] fix cluttered VCS output for other VCSes than git
- [ ] do not print warning when using --yaml (or print to stderr)

I can work on this later today.

**Comment by wkentaro** [comment]
I changed to use write to stderr, because it seems common in wstool package.

**Comment by tkruse** [comment]
Thanks. 

This is not just important to be consistent with the rest of wstools. If you do not know what difference it makes, consider reading up on stderr, like here:
http://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout
http://stackoverflow.com/questions/4919093/should-i-log-messages-to-stderr-or-stdout

It is possible that you will find other places in wstools where stderr should be used, but is not, feel free to raise an issue when you do see places like that.

**Comment by wkentaro** [comment]
We just need to avoid the warning message to be written when with option --yaml, right?
like:
```
wstool info --yaml > my-workspace.rosinstall
```

**Comment by tkruse** [comment]
Yes, though if it is written to stderr it's okay.
In your example:
```
wstool info --yaml > my-workspace.rosinstall
```
the warning must not end up in my-workspace.rosinstall, but when we use stderr, it will not go into my-workspace.rosinstall.

**Comment by wkentaro** [comment]
yeah.

**Comment by wkentaro** [comment]
Remaining tasks are below?

- fix cluttered VCS output for other VCSes than git

**Comment by tkruse** [comment]
yes, sorry, I will be offline until monday, did not get to work on it yesterday.

**Comment by wkentaro** [comment]
ok, thanks.
that's no problem.

2015年7月31日金曜日、Thibault Kruse<notifications@github.com>さんは書きました:

> yes, sorry, I will be offline until monday, did not get to work on it
> yesterday.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcstools/wstool/pull/42#issuecomment-126568443>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wjwwood** [comment]
What's the state of this? Just waiting on some more improvements before a final review?

**Comment by wkentaro** [comment]
The remaining task is 

* fix cluttered VCS output for other VCSes than git

but I'm not so familiar with other VCSes, so please wait for @tkruse to have time to work for it.

**Comment by tkruse** [comment]
The current commit can already be merged, it is small enough. The additional noisy output is probably difficult to suppress anyways.

**Comment by wjwwood** [comment]
Ok, sounds good to me. Thanks guys.

**Comment by wjwwood** [comment]
I'm going to try and do a release of `wstool` this week, so if there's dangling stuff you'd like in the next release lets wrap them up. I know much of it is probably waiting on me to review and I'll do that for anything that's ready before a release. Thanks for your patience.

**Comment by tkruse** [comment]
Releasing sounds good. Sadly I notice there are some long standing PRs (#22 and #95) that never made it into a merge, not sure what to do about them. In any case #96 and #99 could still be merged, I made a new PR for #96 and added documentation for the API changes.

The rosws documentation is also affected (since rosws info and set use shared code with wstool. wstool itself does not have doumentation (Guess I forgot). It can probably largely be copied from rosws.

**Comment by tkruse** [comment]
changelog also needs updating, want a PR?

**Comment by wjwwood** [comment]
I'll review the changelog as I'm releasing, but if you'd like to get something in the changelog specific I'd appreciate a pr.

**Pull request merged**
