### PR TITLE
Stop creating new file for soft linked config file

### LINKED ISSUE #58: soft link .rosinstall does not work
wstool creates .rosinstall as new file so the soft link breaks after wstool set/rm.
the usecase is like:
https://github.com/vcstools/wstool/issues/29#issuecomment-65289108

so, I'm changing to open the realpath of config file. at here:
https://github.com/vcstools/wstool/blob/master/src/wstool/config_yaml.py#L373

any idea?

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #58

* just copy .rosinstall to .rosinstall.bak (so .rosinstall.bak is not soft link)
* edit realpath of .rosinstall (it does not break soft link)

### CODE REVIEW

**Comment by wkentaro** [comment]
@tkruse 
Could you please review this?

**Comment by tkruse** [comment]
lgtm, but one instance of shutil.move probably also needs fixing in rosws (rosinstall_cli.py), for consistency. But that can be a separate PR.

**Comment by wkentaro** [comment]
Thanks, so can you review and merge if it is fine? @wjwwood

**Comment by wjwwood** [comment]
@wkentaro will do asap. Realistically it will be after ROSCon.

**Comment by wkentaro** [comment]
I see your busy status. I can wait for that.

On Fri, Oct 2, 2015 at 3:25 PM, William Woodall <notifications@github.com>
wrote:

> @wkentaro <https://github.com/wkentaro> will do asap. Realistically it
> will be after ROSCon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vcstools/wstool/pull/69#issuecomment-144935174>.
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
Ping.

**Pull request merged**
