### PR TITLE
Generate man page in building

### PR DESCRIPTION
**Pull request by wkentaro**
To generate

```
$ make build_manpage
```

The output of `$ man wstool`
image

### CODE REVIEW

**Comment by wkentaro** [comment]
I'm also changing completion files location
`completion/_wstool` -> `extra/completion/_wstool`

**Comment by tkruse** [comment]
Is that better than:
```
cd doc
make man
```
?

**Comment by wkentaro** [comment]
I mean this is to install manpage via pip as well as completion scripts.

**Comment by tkruse** [comment]
Ah, now I see, Sorry. 
So a small dirty thing is having the generated manfile in git. I would prefer not to have it in git, possibly by raising an error in setup.py if it does not exist, telling the releaser to create the manfile to release. Else the manfile will easily become outdated.

**Comment by wkentaro** [comment]
Fixed.

**Comment by wjwwood** [comment]
I agree, with @tkruse, the man file should be generated before installation. Ideally it would also work when being installed from `pip`, so it wouldn't be a manual step that has to be done before running the `setup.py`. Maybe the setup.py should build the man file as part of the build step. Maybe something in this vein: http://stackoverflow.com/questions/11331175/hook-to-add-commands-to-distutils-build

**Comment by wkentaro** [comment]
I'm done. Please review.

as discussed here: https://github.com/pypa/pip/issues/2381
no way to declare dependencies for build time.

**Comment by wkentaro** [comment]
Rebased with the commit on #39 .
Please review.

**Comment by wjwwood** [comment]
Does this need a rebase since #39?

**Comment by wjwwood** [comment]
Sorry, missed your comment. Reviewing now.

**Comment by wkentaro** [comment]
I think so. This also needs to use the function `_resolve_prefix()` to install man page to desired destination.

**Comment by wjwwood** [comment]
Ok, it looks good to me and I tried it out locally and behaves as I would expect in a few cases. I did have to use `--old-and-unmanageable` in order to prevent it from making an `.egg` file in one case.

When installing to my system python I got this error:

```
error: can't copy 'build/sphinx/man/wstool.1': doesn't exist or not a regular file
```

Here's the whole output: https://gist.github.com/wjwwood/dda002613f3a7c67d655

**Comment by wjwwood** [comment]
Looks like `build_man` is not getting invoked when you just do install. If I do `python setup.py build` it does get invoked, but just doing `python setup.py install` does not work.

**Comment by wkentaro** [comment]
Yeah, thanks. 
I need to overwrite build_py command as well as build.

**Comment by wjwwood** [comment]
Ok, it works for me now. +1

**Comment by wjwwood** [comment]
Thanks for taking the time to figure out how to generate it at build time.

**Comment by wkentaro** [comment]
:+1:

**Comment by wjwwood** [comment]
@wkentaro I just released `0.1.7`, but when installing from `pip` I get:

```
% sudo -H python -m pip install wstool
Collecting wstool
/Library/Python/2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading wstool-0.1.7.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 833kB/s
Requirement already satisfied (use --upgrade to upgrade): vcstools>=0.1.37 in /Library/Python/2.7/site-packages (from wstool)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /Library/Python/2.7/site-packages (from wstool)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /Library/Python/2.7/site-packages (from vcstools>=0.1.37->wstool)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil->vcstools>=0.1.37->wstool)
Installing collected packages: wstool
  Running setup.py install for wstool
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Mus3aQ/wstool/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VSaPaC-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_man
    creating /private/tmp/pip-build-Mus3aQ/wstool/build
    creating /private/tmp/pip-build-Mus3aQ/wstool/build/sphinx
    creating /private/tmp/pip-build-Mus3aQ/wstool/build/sphinx/doctrees
    creating /private/tmp/pip-build-Mus3aQ/wstool/build/sphinx/man
    Running Sphinx v1.3.1
    error: conf.py: No such file or directory

    ----------------------------------------
Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Mus3aQ/wstool/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-VSaPaC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Mus3aQ/wstool
```

I missed this in my original testing. It might be because this pr is assuming you're running from within the `wstool` source?

**Comment by wkentaro** [comment]
Sorry about that. I think it is because `doc/` is missing in MANIFEST.in.

**Comment by wkentaro** [comment]
I'm working on this now.

**Comment by wjwwood** [comment]
Thanks. I was slowly coming to the same conclusion.

**Comment by wjwwood** [comment]
Let me know when you think you have a fix and I'll roll another release.

**Comment by wkentaro** [comment]
@wjwwood  I sent pr: #61

**Comment by wjwwood** [comment]
Ok, `0.1.8` seems to work:

```
% sudo -H python -m pip install -U wstool
Password:
Collecting wstool
/Library/Python/2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading wstool-0.1.8.tar.gz (51kB)
    100% |████████████████████████████████| 53kB 1.2MB/s
Requirement already up-to-date: vcstools>=0.1.37 in /Library/Python/2.7/site-packages (from wstool)
Requirement already up-to-date: pyyaml in /Library/Python/2.7/site-packages (from wstool)
Requirement already up-to-date: python-dateutil in /Library/Python/2.7/site-packages (from vcstools>=0.1.37->wstool)
Requirement already up-to-date: six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil->vcstools>=0.1.37->wstool)
Installing collected packages: wstool
  Running setup.py install for wstool
Successfully installed wstool-0.1.8

william@farl ~
% sudo -H python -m pip uninstall wstool
Uninstalling wstool-0.1.8:
  /Library/Python/2.7/site-packages/wstool-0.1.8-py2.7.egg-info
  /Library/Python/2.7/site-packages/wstool/__init__.py
  /Library/Python/2.7/site-packages/wstool/__init__.pyc
  /Library/Python/2.7/site-packages/wstool/__version__.py
  /Library/Python/2.7/site-packages/wstool/__version__.pyc
  /Library/Python/2.7/site-packages/wstool/cli_common.py
  /Library/Python/2.7/site-packages/wstool/cli_common.pyc
  /Library/Python/2.7/site-packages/wstool/common.py
  /Library/Python/2.7/site-packages/wstool/common.pyc
  /Library/Python/2.7/site-packages/wstool/config.py
  /Library/Python/2.7/site-packages/wstool/config.pyc
  /Library/Python/2.7/site-packages/wstool/config_elements.py
  /Library/Python/2.7/site-packages/wstool/config_elements.pyc
  /Library/Python/2.7/site-packages/wstool/config_yaml.py
  /Library/Python/2.7/site-packages/wstool/config_yaml.pyc
  /Library/Python/2.7/site-packages/wstool/helpers.py
  /Library/Python/2.7/site-packages/wstool/helpers.pyc
  /Library/Python/2.7/site-packages/wstool/multiproject_cli.py
  /Library/Python/2.7/site-packages/wstool/multiproject_cli.pyc
  /Library/Python/2.7/site-packages/wstool/multiproject_cmd.py
  /Library/Python/2.7/site-packages/wstool/multiproject_cmd.pyc
  /Library/Python/2.7/site-packages/wstool/ui.py
  /Library/Python/2.7/site-packages/wstool/ui.pyc
  /Library/Python/2.7/site-packages/wstool/wstool_cli.py
  /Library/Python/2.7/site-packages/wstool/wstool_cli.pyc
  /etc/bash_completion.d/wstool-completion.bash
  /usr/local/bin/wstool
  /usr/share/man/man1/wstool.1
  /usr/share/zsh/site-functions/_wstool
Proceed (y/n)? n
```

The shell completion and man pages seem to be there.

**Comment by wjwwood** [comment]
The deb is there too.

**Comment by wkentaro** [comment]
Thanks.

**Comment by tkruse** [comment]
@wkentaro if you like, you could announce the changes to wstool on ros-users list.

**Comment by tkruse** [comment]
I mean, once 0.1.8 is available on pip

**Comment by wjwwood** [comment]
`0.1.8` should be available for `pip` and from `apt-get` already:

```
% sudo -H python -m pip install wstool
Collecting wstool
/Library/Python/2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached wstool-0.1.8.tar.gz
Requirement already satisfied (use --upgrade to upgrade): vcstools>=0.1.37 in /Library/Python/2.7/site-packages (from wstool)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /Library/Python/2.7/site-packages (from wstool)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /Library/Python/2.7/site-packages (from vcstools>=0.1.37->wstool)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /Library/Python/2.7/site-packages (from python-dateutil->vcstools>=0.1.37->wstool)
Installing collected packages: wstool
  Running setup.py install for wstool
Successfully installed wstool-0.1.8
```

**Comment by tkruse** [comment]
@wkentaro : if you do not want to announce on git-user, please say so. Then I will do unless @wjwwood wants to.

**Comment by wkentaro** [comment]
Could you please do that? I'm not familiar to that mailing list.

**Comment by tkruse** [comment]
I do not see the man page included in  the pip or debian package.

**Comment by wkentaro** [comment]
That is generated at build time if you have installed sphinx already.
so after installing sphinx, you can generate and install manpage by pip install wstool.

**Comment by wjwwood** [comment]
Maybe I just need to make sure Sphinx is installed when I build the deb. I'll look into it tomorrow.

**Pull request merged**
