### PR TITLE
Enhance: `-u` | `--update` option for `wstool set`

### PR DESCRIPTION
**Pull request by wkentaro**
issue: https://github.com/vcstools/wstool/issues/48
auto updating repository after setup.

### CODE REVIEW

**Comment by wkentaro** [comment]
The stdout is like below:

```
% wstool set wkentaro/wstool https://github.com/wkentaro/wstool.git --git --update

     Add new elements:
  wkentaro/wstool   	git  https://github.com/wkentaro/wstool.git

Continue: (y)es, (n)o: y
Overwriting /Users/ken/ws/.rosinstall
[wkentaro/wstool] Updating /Users/ken/ws/wkentaro/wstool
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/wkentaro/wstool
 * [new branch]      wstool-set-update-option -> origin/wstool-set-update-option
[wkentaro/wstool] Done.

update complete.
```

**Comment by wkentaro** [comment]
With wrong uri,

```
wstool set wkentaro/wstool https://github.com/wkentaro/hogehoge.git --git --update

     Add new elements:
  wkentaro/wstool   	git  https://github.com/wkentaro/hogehoge.git

Continue: (y)es, (n)o: y
Overwriting /Users/ken/ws/.rosinstall
ERROR in config: Failed to install tree '/Users/ken/ws/wkentaro/wstool'
 Aborting install because of Url https://github.com/wkentaro/wstool.git does not match https://github.com/wkentaro/hogehoge.git requested.
```

**Comment by wkentaro** [comment]
With this option, user can download repo quickly and so confirm the set uri actually exists.

**Comment by wjwwood** [comment]
lgtm, I'll go ahead and merge, if anyone else has comments we can handle them after the fact.

**Pull request merged**
