### PR TITLE
[WIP] Option to show simplified version info table

### PR DESCRIPTION
**Pull request by wkentaro**
**before**
```
$ wstool info
```
screen shot 2016-02-21 at 1 12 17 am

**after**
```
$ wstool info --short
```
screen shot 2016-02-21 at 1 12 28 am

### CODE REVIEW

**Comment by tkruse** [comment]
Hi,

thank you for the pull request. If you make a separate PR for all the refactorings (space, orderedDict, orderedDict for Python2.6), then those can be merged independently.

The actual feature --short may be useful, but I have two minor concerns. First, it duplicates existing functionality of --only, and second it is not very customizable or self-explaining. The selection of columns for a "short" view may be a personal thing, I am not sure if a useful consensus is possible.

Now --only is probably a bit clumsy for everyday use.

So some alternatives to compare to:
- use something similar to verbosity levels with number indicating how many of the default columns to show (requires strange semantics of which columns "appear" first)
- use predefined table-layouts, such that -l1 could be "layout 1", meaning "short version"
- use a command like --versions that convey better than "--short" what to expect

I'll let William decide on how to proceed, this could be simply merged, discussed further here, or taken to the buildsystem SIG for more opinions. It's a tiny feature in any case, and prone to bike-shedding (I plead guilty).

**Comment by wkentaro** [comment]
Thanks for the comment, I separated the refactoring as another PRs.

**Comment by wkentaro** [comment]
> The actual feature --short may be useful, but I have two minor concerns. First, it duplicates existing functionality of --only, and second it is not very customizable or self-explaining. The selection of columns for a "short" view may be a personal thing, I am not sure if a useful consensus is possible.

I think your concerns are reasonable, I have an option to add `--columns` argument with similar feature as `--only` but not CSV style but table.
But if the selected columns by users are consistent, adding `--short` or `--simple` option seems better like `git status --short` option.

**Comment by tkruse** [comment]
I agree "-s" is very convenient for the use-case. Let @wjwwood decide whether to just merge or have some further discussion.

**Comment by wjwwood** [comment]
This makes sense to me. I tried it out locally and without `-s` I can't even read the output from an indigo-desktop-full workspace. I had to rebase and merge some conflicts. Please have a look at https://github.com/vcstools/wstool/commit/249a9fdbd6a2de06d92a2cb85a42f8099ce00c8f to make sure I did it right.

**Pull request merged**
