### PR TITLE
Add wstool completion

### PR DESCRIPTION
**Pull request by wkentaro**
Issue: https://github.com/vcstools/wstool/issues/32

### CODE REVIEW

**Comment by wjwwood** [comment]
Code changes lgtm, with the caveats mentioned in the other thread. I haven't tried it out yet.

**Comment by tkruse** [comment]
+1 I think. What about zsh?

**Comment by wkentaro** [comment]
I think zsh users should manually source the completion script, 
or we should send pr to popular completion plugins like 
https://github.com/zsh-users/zsh-completions .

**Comment by tkruse** [comment]
I see, there is no similar way as for bash.

**Comment by wkentaro** [comment]
asap, yes.

**Comment by tkruse** [comment]
Hm, but what vcstool does, is to install the completion scripts anyway.
See https://github.com/dirk-thomas/vcstool

So maybe the files that do not go to bash-completion.d could go to the other place (/usr/share/wstool-completion) instead?

**Comment by wkentaro** [comment]
In that case, I think users have to manually source that scripts in their `.bashrc` or `.zshrc`.
(I tried installing vcstool in my environment, but there was no completion with just installing.)

**Comment by tkruse** [comment]
yes, that's how it would work.

**Comment by wkentaro** [comment]
I now understand what you mean.

I made another implementation to install completion functions.
Please see: https://github.com/vcstools/wstool/pull/39

With the new implementation, bash completion script is not automatically sourced, so users should do.
In darwin, `/usr/local/etc/bash_completion.d` is not registered as default but `/etc/bash_completion.d`.
As for darwin, I think it is common to register `/usr/local/etc/bash_completion.d` as completion location, so most bash users should register.

But it's simpler and zsh users does not needed to add any changes to their config file.

**Comment by wkentaro** [comment]
What about this as another alternative?
I'd like to install completion scripts to common location as far as possible in order not to source manually.

**Comment by tkruse** [comment]
I prefer #39 to #33. @wjwwood ?
As usual, it would be great to have a standard practice within the ROS community.

**Comment by wjwwood** [comment]
It would be nice to have a library for this, maybe it's a candidate for inclusion in our catch all utility python package: https://github.com/osrf/osrf_pycommon Or maybe it's generally useful and should be it's own Python package.

At the very least, it's not clear to me that we're doing it "correctly" in any one place.

That all being said, I agree that for this decision #39 is a better solution.

**Comment by wkentaro** [comment]
You mean a function like `distutils.sysconfig.get_python_lib()`, don't you?
I posted to bugs.python.org http://bugs.python.org/issue24753 .

I'm thinking add function like below:
```
import os
import platform


def get_completion_install_location(shell):
    prefix = ''
    if os.getuid() == 0:
        # running as root
        uname = platform.uname()[0]
        if uname == 'Linux':
            prefix = '/'

    if shell == 'bash':
        location = os.path.join(prefix, 'etc/bash_completion.d')
    elif shell == 'zsh':
        location = os.path.join(prefix, 'share/zsh/site-functions')
    else:
        raise ValueError('unsupported shell: {0}'.format(shell))

    return location
```

(It seems that osrf_pycommon has not been released yet at pypi.)

**Comment by wkentaro** [comment]
the issue is rejected: http://bugs.python.org/issue24753
so could you please release osrf_pycommon?

**Comment by wkentaro** [comment]
Now I think the function `get_completion_install_location()` is used in setup.py.
so it cannot depend on packages which is not assumed be installed (standard libraries, setuptools).

I updated again https://github.com/vcstools/wstool/pull/39 , so please review it.
If it is fine, please merge.

To try installing:
```
$ pip install https://github.com/wkentaro/wstool/archive/another-wstool-completion.zip
```

**Comment by wjwwood** [comment]
> so could you please release osrf_pycommon?

I'll probably release it soon since the new functionality in `catkin_tools` makes use of it.

> I updated again #39 , so please review it.

Will do, I'm going to close this one in favor of #39. We can reopen it if that's not right.

**Pull request closed without merging**
