### PR TITLE
Add fake identity for VCSs

### PR DESCRIPTION
**Pull request by jspricke**
This makes the unit tests self contained.

### CODE REVIEW

**Comment by wjwwood** [comment]
I updated the travis settings to only test current versions of Python which should fix the setup issues in CI, but several of the matrix entries just have failing tests.

**Comment by jspricke** [comment]
Looks like your update hid the test output and made Travis green :). For comparison, this is the corresponding Debian build log with the change and test output: https://buildd.debian.org/status/fetch.php?pkg=ros-wstool&arch=all&ver=0.1.13-3&stamp=1500371291&raw=0. It's running `python3.6 -m unittest discover -v`, maybe we should do that as well?

**Comment by wjwwood** [comment]
> Looks like your update hid the test output and made Travis green :).

Good catch, it looks like coverage is not installed for some reason. It's really bad behavior that it shows all tests passing because it couldn't import coverage.

> It's running `python3.6 -m unittest discover -v`, maybe we should do that as well?

I don't think we need to do that. `nosetest` should as it was before.

**Comment by wjwwood** [comment]
Hmm, it seems like `python setup.py nosetest` is not working correctly... it might be a setting in the setup.py that is affecting this. I'll have to debug it some more. Maybe I'll switch to the `unittest` invocation that @jspricke suggested, but I wanted to keep nosetest in case it was using some nosetest specific API in the tests (I didn't check for this yet).

**Comment by wjwwood** [comment]
Ok, sorry, I got the tests running again (the test layout was confusing nosetest). I couldn't use your suggested invocation @jspricke because it doesn't do the coverage stuff I think.

Now that the tests are running again, it is failing with the no author issue. Can you have another look?

**Comment by jspricke** [comment]
@wjwwood thanks for fixing Travis. This should be fine now.

**Comment by wjwwood** [comment]
@jspricke thank you for iterating on it!

**Pull request merged**
