### PR TITLE
foreach command: add -v, -m, and -j options

### PR DESCRIPTION
**Pull request by NikolausDemmel**
```
--verbose, -v    print to stdout as commands are executed, not just at the end
--timeout, -m    timeout for commands in seconds
--jobs, -j       limit number of parallel executions; default is 1
```
One notable change of default behaviour: `-j 1` (like for `init` and `update`) is default now, but previously it used to be fixed parallel execution (I think with 10 threads).

**EDIT:** One more change: The return code of the wstool invocation is now only 0, if all commands have 0 retrun code, else it is 1. It used to be always 0.

### CODE REVIEW

**Comment by tkruse** [comment]
code lgtm.

I assume the main reason for changing to 1 thread as default is to make the behavior consistent with other commands.

Regarding the return code, I am slightly worried whether other commands behave differently, would be worth checking to make it consistent if not, but should not prevent this PR from being merged.

**Comment by NikolausDemmel** [comment]
> I assume the main reason for changing to 1 thread as default is to make the behavior consistent with other commands.

Yes. Consistency is one reason. I personally think 1 is a better default. But I wouldn't object to changing it to something else if others think differently.

> Regarding the return code, I am slightly worried whether other commands behave differently, would be worth checking to make it consistent if not, but should not prevent this PR from being merged.

I haven't really investigated, but at least [update does the same](https://github.com/vcstools/wstool/blob/249a9fdbd6a2de06d92a2cb85a42f8099ce00c8f/src/wstool/multiproject_cli.py#L1032-L1049). I'm not very attached to that part of the PR. May main motivation was to get `-j`, since with the current default parallel execution I have calls like `wstool foreach 'git remote update -p'` on a workspace with 25+ repos failing all the time with connection timeouts (admittedly that is on a slow VM, under Windows, with VPN, and proxy...)

**Comment by NikolausDemmel** [comment]
@wkentaro as the original author of `foreach`, do you have any objections about the `-j 1` default as well as the exit code to indicate success of all executed commands?

**Comment by wkentaro** [comment]
@NikolausDemmel I agree with your general idea, and the defaults of -j
option and the exit code.

On Thu, Mar 24, 2016 at 8:13 PM, Nikolaus Demmel <notifications@github.com>
wrote:

> @wkentaro <https://github.com/wkentaro> as the original author of foreach,
> do you have any objections about the -j 1 default as well as the exit
> code to indicate success of all executed commands?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/vcstools/wstool/pull/88#issuecomment-200793306>
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wjwwood** [comment]
Code changes lgtm. I don't have a preference for what the parallelism is by default, so I'll just merge this as is. If collectively we come to some other conclusion we can make a follow up change.

**Comment by wjwwood** [comment]
@NikolausDemmel thanks for the contribution. Sorry it took so long for me to get to it. I'll try to make a release sometime mingled within the other indigo/jade/kinetic releases I have to do.

**Comment by NikolausDemmel** [comment]
Thanks @wjwwood and thanks @tkruse and @wkentaro for reviewing.

**Pull request merged**
