### PR TITLE
Add export command

### PR DESCRIPTION
**Pull request by rsinnet**
Apologies for not getting around to this sooner. This is the proper fix for #116. I reverted the revert from #117 and then added the fix as a second commit (4be09620b5c263d17a1a5d0c3b64f1e212980196). The root cause was a circular dependency introduced in `config_yaml.py`. This was only used to do an `isinstance` assert that I added in #98. Since this assert isn't necessary or even necessarily helpful in production, I simply removed it.

### CODE REVIEW

**Comment by rsinnet** [comment]
@wjwwood Sorry for not getting around to this sooner, let me know if there's anything else I can do.

**Comment by wjwwood** [comment]
No worries, thanks for coming back around to it. I considered a similar fix, but I didn't know if the assert was important or not.

**Review by wjwwood — APPROVED** [review]
lgtm

**Comment by wjwwood** [comment]
Hmm, I tried testing this with `pyenv` (installing just `wstool` from this pr and `rosinstall` from `pip`), and I get this:

```
% /Users/william/.pyenv/versions/2.7.14/bin/rosws
Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/2.7.14/bin/rosws", line 52, in <module>
    import rosinstall.rosws_cli
  File "/Users/william/.pyenv/versions/2.7.14/lib/python2.7/site-packages/rosinstall/rosws_cli.py", line 53, in <module>
    from wstool.multiproject_cmd import get_config, cmd_install_or_update, \
ImportError: cannot import name cmd_snapshot
```

These are the steps I took:

- install `pyenv` (if you don't have it already)
- `pyenv install 2.7.14`
- `mkdir -p /tmp/testing_120`
- `cd /tmp/testing_120`
- `git clone https://github.com/vcstools/wstool`
- `cd wstool`
- `git checkout -b rsinnet-add_snapshot_command master`
- `git pull https://github.com/rsinnet/wstool.git add_snapshot_command`
- `eval "$(pyenv init -)"`
- `which python`  # should be in `~/.pyenv/shims`
- `python ./setup.py install`
- `python -m pip install rosinstall`
- `which wstool`  # should be in `~/.pyenv/shims`
- `wstool`
- `which rosws`  # should be in `~/.pyenv/shims`
- `rosws`

But the last command gives me the above error still.

**Comment by rsinnet** [comment]
Okay here's the low-down: When I initially add the `export` command, I had observed that the code contained the beginnings of a `snapshot` command. So I implemented it as snapshot but renamed it export per Tulley's suggestion (https://github.com/vcstools/wstool/pull/98#issuecomment-263505950) for consistency with `vcs`. In my implementation, I repurposed the bit of code involving `cmd_snapshot` to reduce code entropy and so I renamed it to `cmd_export`.

**Comment by rsinnet** [comment]
A thought on testing: since `rosinstall` depends on `wstool`, we could add a line to the CI yml to install `rosinstall` through `pip` and then add a simple smoke test. It's a bit dirty but it would catch some compatibility errors. Thoughts?

**Comment by wjwwood** [comment]
> A thought on testing: since rosinstall depends on wstool, we could add a line to the CI yml to install rosinstall through pip and then add a simple smoke test. It's a bit dirty but it would catch some compatibility errors. Thoughts?

Fine by me, sounds like a good idea. 👍

**Comment by wjwwood** [comment]
Btw, is this ready for re-review?

**Comment by rsinnet** [comment]
If we agree with the proposed fix, then yes. If you want me to implement the smoke test, I could do that this weekend and could include in this pull request.

**Comment by wjwwood** [comment]
If you have time for the smoke test that would be nice to have. If not just let me know and I'll review this again as-is.

**Comment by rsinnet** [comment]
I'm happy to do the smoke test, so please wait on that.

**Comment by rsinnet** [comment]
Added the smoke test, seems to work. Ready for review. Let me know what you think. @wjwwood

**Comment by rsinnet** [comment]
Bump! Just a friendly reminder :smiley: @wjwwood

**Comment by rsinnet** [comment]
bump

**Comment by wjwwood** [comment]
Thanks @rsinnet, sorry for the lag and for the new smoke test.

**Pull request merged**
