### PR TITLE
Install man & completion to outside of system to avoid SIP

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wjwwood** [comment]
Presumably we didn't do it this way to begin with, so what is the downside to defaulting to `/usr/local`?

I still think it's necessary, but I was just wondering what else users need to do or need to be aware of after this change.

**Comment by tfoote** [comment]
Please reference the issue and link to info on SIP, it's an acronym with lots of meanings.

**Comment by wkentaro** [comment]
> Please reference the issue and link to info on SIP, it's an acronym with lots of meanings.

I updated.

**Comment by wkentaro** [comment]
> Presumably we didn't do it this way to begin with, so what is the downside to defaulting to /usr/local?
I still think it's necessary, but I was just wondering what else users need to do or need to be aware of after this change.

/usr/share/zsh/site-functions is default location for completion on zsh which is preinstalled on OS X.
on the other hand, /usr/local/share/zsh/site-functions is default location for completion on zsh which is usually installed via Homebrew.

So, by this change, completion will not work for users who use default zsh on OS X.

**Comment by wjwwood** [comment]
@wkentaro I think that's a fair trade-off and it works around the system integrity protection issue. So I'll merge this and I'll update the docs before doing a release, making note that users of the system `zsh` on OS X need to take an extra step in order to get shell completion.

**Comment by wkentaro** [comment]
@wjwwood Thanks.

**Pull request merged**
