### PR TITLE
Check also tracking versions

### PR DESCRIPTION
**Pull request by wkentaro**
image

### CODE REVIEW

**Comment by wkentaro** [comment]
Relates to: https://github.com/vcstools/wstool/issues/34

Difference between local and tracking is not yet implemented in `vcstools/vcstools`.
So I may create PR.

**Comment by tkruse** [comment]
Hi, do you have the vcstools changes for git on a public repository somewhere? I might have some time to write the code for the other VCSes

**Comment by wkentaro** [comment]
I used existing method of vcstools to get tracking branch.
https://github.com/vcstools/wstool/pull/35/files#diff-51883781d8f0bf3409cca3003c73d70fR442

However, `get_branch_parent` method is implemented only for git in vcstools.
So the TODO are below I think.
1.  make compatible `get_branc_parent` with vcstools other than git
2.  check the diff from tracking branch by implementing method like `get_diff_parent`

**Comment by tkruse** [comment]
I see, ok.

**Comment by wjwwood** [comment]
@wkentaro thanks for the pr. It looks like there is one failing test, could you have a look and see if your pull request is to blame?

https://travis-ci.org/vcstools/wstool/jobs/70765916#L1520

**Comment by tkruse** [comment]
Hi,

So the current PR shows what could be done, though it should not be merged, as it uses an internal API of vcstools.


Regarding the functionality, I now see that it does not fix #34, but a different use case. The output:
```
Version-Spec: master
Tracking: master
```

is in 99% of cases non-interesting. It does not tell the user whether there are updates on remote, and Tracking will most commonly be the same as Version-Spec. For these cases, the info command currently uses the bracket notation:
```
UID (Spec):  a1b2c3d4     # current UID and Spec UID are same, so no need to display twice.
UID (Spec):  a1b2c3d4 (e5f6g7h8)    # current UID and Spec UID are different
```

I would suggest this kind of output for the name of the version spec as well, such as "Version-Spec (remote)". As a header that's quite long, not sure how to deal with that.

**Comment by tkruse** [comment]
The longer I think about it, the more it seems to me that what this PR does is to make wstool info give arbitrary extended information about the current branch. Before this PR, wstool info does not show which branch a user is working on. With this PR, it would show which remote branch the current branch is tracking (which most commonly has the same name as the local branch). Just as interesting could be to know which remote is being followed, where people have their own forks on github.
Basically the full output of ```git branch -vv --no-color``` for the current branch. None of that information is currently shown (current branch, tracked remote, tracked branch, divergence status).

However that is quite a lot of information to put into the ```wstool info``` output.

So the idea to compress the output is again to only show things that are out of the ordinary. So an ordinary workspace would have a small table, a weird workspace would have an ugly table. I could live with that.

As an example, given the following output:
```
$ git branch -vv --no-color
* master 8e7355e [origin/master: ahead 1, behind 2]
```
Then the first 'master' should not be shown unless the .rosinstall has a version attribute and it is not 'master'.
the commit ID we already show.

The remote 'origin' should be hidden unless it is something else than 'origin'
The tracked branch 'master' should be hidden unless it is different from the branchname.
'ahead 1, behind 2' should go into the version flag 'C' as described in #34 

So, the worst case could be:
```
$ git branch -vv --no-color
* foo 8e7355e [mine/bar: ahead 1, behind 2]
```

In which case I would hope for an output like:
```
Version (Spec)
foo < mine/bar (master) 
```
indicating I am on branch foo tracking mine/bar, but the .rosinstall says version should be master

So this would require implementing the call to ```git branch -vv --no-color``` in vcstools, and writing some logic to hide/compress output.

**Comment by tkruse** [comment]
So I started implementing this for git, but it turns out that the ```git branch -vv``` command is not well written to be parsed.
In particular the commit message is added at the end, but the commit message can easily be written in a format that looks like git information:

```
master 8e7355e [origin/master] msg
foo a1b2c3d4 [fixes #1234] rest of message
```
That's a real bummer, so we'd need to invoke several commands.
To get the current branch, we can use GitClient.get_branch()
To get the tracked branch we can use GitClient.get_branch_parent()

To indicate divergence, we can use:
```
git rev-list <branch> --not <branch_parent>      # for local additions
git rev-list <branch_parent> --not <branch>      # for remote additions
```

**Comment by tkruse** [comment]
Hi Kentaro,

I created changes on branches named 'divergence' for both vcstools and wstool (without unit tests and other VCSes).
See:
 * https://github.com/tkruse/vcstools/tree/divergence
 * https://github.com/tkruse/wstool/tree/divergence

The output looks like this:
```
 Localname S SCM  Version (Spec)                 UID  (Spec)  URI  (Spec) [http(s)://...]
 --------- - ---- --------------                 ----------- ---------------------------
 vcstols   C git  master  (-)                    9726de6b850b git@github.com:vcstools/vcstools.git
 vcstols1    git  <detached>  (-)                8e7355e2095e git@github.com:vcstools/vcstools.git
 vcstols2  V git  local_force < fix_force  (foo) a0a5457bd192 git@github.com:vcstools/vcstools.git
```

So I implemented the 'C' attribute in the column for divergence (though the rest of the table does not show more about it), and the 4th column now always shows the current branchname, and the branchname specified in the spec, or '(-)' if none was specified. In the case a local branch tracks a remote branch of a different name, this is indicated with the '<' symbol. Detached local git repositories are listed as ```<detached>```

I generally like the additional information, though more manual testing and more unit tests are required, and implementations are still required for the other VCSes.

**Comment by tkruse** [comment]
The main problem with this solution is that formally, a fetch would be required for each git repository, else the remote branch could move ahead without us noticing. However, a fetch would make the wstool info command much slower. I believe the additional C status is valuable even without fetch, but some people might be led to believe there is nothing new on remote, while there is. 

Alternatives would be having either an extra command for fetching (updating metadata from remotes), or to have an additional option in the info command to do the fetching (or to show divergences, which would imply fetching). I am not sure yet which I prefer.

Can you at least confirm the display behavior is suitable for you?

**Comment by wkentaro** [comment]
> is in 99% of cases non-interesting. It does not tell the user whether there are updates on remote, and 

What you are saying is reasonable and the Tracking-branch should be of the current branch for the usefulness.

> Can you at least confirm the display behavior is suitable for you?

Yes, the output is quite useful.
Sometimes the version-spec is not specified, but if the tracking-branch of current branch is correct (usually `origin/master`) there is no problem.
So displaying 
* current branch (ex `foo`)
* tracking branch of current branch (ex `origin/foo`)
is helpful, I think.

**Comment by wkentaro** [comment]
Maybe,
```
$ git branch -vv --no-color
* foo 8e7355e [mine/bar: ahead 1, behind 2]
```
should be displayed as 

```
Version (Spec)
foo <> mine/bar (master) 
```

and `<<` means behind, `>>` means ahead, and `<>` means both direction difference.

**Comment by tkruse** [comment]
Regarding the tracking branch: I believe if a repository is on master, we should not display anything if it is tracking origin/master, because that is the non-interesting default. Maybe we can display something if a branch is not tracking anything, as an indication of weirdness that the user should pay attention to.

Regarding the extended divergence status ```<< >> <>```:
The function that computes whether there are changes with remote currently is in common_cli, and it merely compares the SHA-IDs, which is cheap. Comparing which is ahead is possible as I explained before, but requires several more API changes, and more complex logic for the other VCSes. I believe it is easier for users to check for themselves what goes on there, when they see the 'C'. Since the C is so cheap to implement, we can first work to make the current state viable for merging (adding tests and implementing the other VCSes). Extending the status could then be a second step.

**Comment by wkentaro** [comment]
> we should not display anything if it is tracking origin/master

yeah, I think that's a good idea not to mess up the info table, and make it simple.

> Regarding the divergence:

I see. As you said, checking ahead or behind may be not so important in some cases, and it is time consuming if using `git rev-list` command to check.

I think the display output is fine for me and useful for other users.
Are there anything I can do for this feature?

**Comment by tkruse** [comment]
There is plenty to do. We can work on my divergence branches, you can do
PRs to those. The vcstools API needs to be tested. For wstools, the tests
may need to be fixed, and maybe extended to cover more cases.

I can look at the other VCSes, unless you know one of those well.

**Comment by wkentaro** [comment]
> There is plenty to do. We can work on my divergence branches, you can do
PRs to those. The vcstools API needs to be tested. For wstools, the tests
may need to be fixed, and maybe extended to cover more cases.

Okay, I will work around the branch.

> I can look at the other VCSes, unless you know one of those well.

I'm only familiar with `git`, not very with others, so I'm glad if you work around other VCSes.

**Comment by tkruse** [comment]
closing in favour of #38

**Pull request closed without merging**
