### PR TITLE
Scrape command

### PR DESCRIPTION
**Pull request by tkruse**
@wjwwood , @vincentrou please review. I did not add --scrape option to init command yet.

### CODE REVIEW

**Comment by NikolausDemmel** [comment]
LGTM, but haven't testet.

**Comment by wkentaro** [comment]
@tkruse 
I used that command and it works.

Are you planning to support a feature to specify repository to add with `wstool scrape`?
like: https://github.com/vcstools/wstool/pull/73#issuecomment-142583458
Also, personally I want scrape command to set version also.
(currently, it does not set version, so I need `wstool set [repo] -v[version]`.)

**Comment by tkruse** [comment]
@wkentaro that's both good points. Those are different use-cases for the scrape tool. Some option to set the version could be tried, though there are some design problems with whether to use SHA-ID, tag or branchname (e.g. in git). Scraping a single repository only (meaning using existing VCS information) may also be interesting. I had no plans to do any of this, but I think PRs would be welcome. 

However for setting the version with scrape, we should first discuss the design before implementing too much, because else PRs might have to be changed a lot.

**Comment by wkentaro** [comment]
I see, so setting version  is difficult at this point.
What about changing it to receive specified repositories like `wstool scrape [OPTIONS] [LOCALNAMES]`? Other commands of wstool have same feature, so I think this is natural and easy to use.

**Comment by tkruse** [comment]
Yes, specifying unmanaged paths instead of scraping all that are found should be simple to implement and understand. There is some ambiguity what to do when specifying a managed repo. I am not sure if you talk about that. It is also easy to implement, but maybe not easy to understand / prevent mistakes. I don't know yet whether it would be good.

**Comment by wjwwood** [comment]
Seems to work for me.

**Comment by vincentrou** [comment]
I had time to test it today but a bit late it seems. So I have created another PR for some modifications #78

**Pull request merged**
